services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: joker_frontend
    environment:
      - NODE_ENV=development
      - PORT=5173
      - HOST=0.0.0.0
      - VITE_API_URL=http://backend:3333
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: joker_backend

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      NODE_ENV: production
      PORT: 3333
      HOST: 0.0.0.0
      LOG_LEVEL: info

      APP_KEY: ${APP_KEY}

      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}

    ports:
      - "3333:3333"

  postgres:
    image: postgres:15
    container_name: joker_db
    restart: always

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
